language: elixir
elixir:
  - 1.3.0
otp_release:
  - 19.0
sudo: false
env:
  - MIX_ENV=test
  - POSTGRES_PASSWORD=""
notifications:
  email: false
addons:
  postgresql: '9.4'
services:
  - postgresql
before_script:
  - mix do ecto.create, ecto.migrate
